name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change this to the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Adjust this command to your project's build command

      - name: Deploy to GitHub Pages
        run: |
          # Move to the build output directory
          cd build  # Adjust this to your build output directory

          # Initialize a new git repository
          git init

          # Set up GitHub user
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add all files
          git add .

          # Commit the files
          git commit -m "Deploy to GitHub Pages"

          # Force push to the gh-pages branch
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
